# Generated by Django 5.0.2 on 2024-03-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('familia', models.CharField(max_length=50, verbose_name='фамилия')),
                ('login', models.CharField(max_length=50, verbose_name='логин')),
                ('parol', models.CharField(max_length=50, verbose_name='пароль')),
                ('mail', models.CharField(max_length=80, verbose_name='почта')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
